# backend:
#   name: git-gateway
#   branch: master

# media_folder: content/images

# collections:
#   - name: "services"
#     label: "Services"
#     description: "All services offered by real-value"
#     folder: "content"
#     create: true
#     fields:
#       - label: "Services"
#         widget: "list"

