backend:
  name: git-gateway
  branch: master

media_folder: src/images

show_preview_links: false

collections:
  - name: "services"
    label: "Services"
    description: "All services offered by real-value"
    media_folder: ""
    public_folder: ""
    path: "{{name}}/index"
    folder: "content/services"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["builder-floors", "affordable-housing", "flats", "commercials"],
          required: true
        }
      - { label: "Body", name: "body", widget: "markdown" }
